codecov:
  branch: master
  require_ci_to_pass: true
  allow_pseudo_compare: true
  allow_coverage_offsets: true

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

ignore:
  - "main.go"
  - "cmd/**"
  - "internal/config/**"
